In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


df=pd.read_csv("IEA-EV-dataEV salesHistoricalCars.csv")
print(type(df))

<class 'pandas.core.frame.DataFrame'>


In [3]:
#Data preprocessing
print(df.isnull().sum())
print(df.duplicated().any())
print(type(df))
#Conclusion: No missing values present in the dataset we can proceed with the data analysis and data prediction

region        0
category      0
parameter     0
mode          0
powertrain    0
year          0
unit          0
value         0
dtype: int64
False
<class 'pandas.core.frame.DataFrame'>


In [4]:
print(df.dtypes)

region         object
category       object
parameter      object
mode           object
powertrain     object
year            int64
unit           object
value         float64
dtype: object


In [5]:
X=df[['region','category','parameter','mode','powertrain','year']]
Y=df['value']

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0,1,2,3,4])],remainder='passthrough')
X=ct.fit_transform(X)
X=X.toarray()
print(X)

from sklearn.model_selection import train_test_split
Xtrain,Xtest,Ytrain,Ytest=train_test_split(X,Y,test_size=0.2,random_state=42)
print(Xtrain)


[[1.000e+00 0.000e+00 0.000e+00 ... 0.000e+00 0.000e+00 2.011e+03]
 [1.000e+00 0.000e+00 0.000e+00 ... 0.000e+00 0.000e+00 2.011e+03]
 [1.000e+00 0.000e+00 0.000e+00 ... 0.000e+00 0.000e+00 2.011e+03]
 ...
 [0.000e+00 0.000e+00 0.000e+00 ... 0.000e+00 0.000e+00 2.023e+03]
 [0.000e+00 0.000e+00 0.000e+00 ... 0.000e+00 0.000e+00 2.023e+03]
 [0.000e+00 0.000e+00 0.000e+00 ... 0.000e+00 0.000e+00 2.023e+03]]
[[0.000e+00 0.000e+00 0.000e+00 ... 0.000e+00 0.000e+00 2.023e+03]
 [0.000e+00 0.000e+00 0.000e+00 ... 0.000e+00 0.000e+00 2.017e+03]
 [0.000e+00 0.000e+00 0.000e+00 ... 0.000e+00 1.000e+00 2.015e+03]
 ...
 [0.000e+00 0.000e+00 0.000e+00 ... 0.000e+00 0.000e+00 2.020e+03]
 [0.000e+00 0.000e+00 0.000e+00 ... 0.000e+00 0.000e+00 2.011e+03]
 [0.000e+00 0.000e+00 0.000e+00 ... 0.000e+00 0.000e+00 2.017e+03]]


In [6]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
Xtrain=sc.fit_transform(Xtrain)
Xtest=sc.transform(Xtest)
print(Xtrain)



[[-0.14552138 -0.15909803 -0.15690944 ... -0.38883626 -0.56087649
   1.48158343]
 [-0.14552138 -0.15909803 -0.15690944 ... -0.38883626 -0.56087649
  -0.10023012]
 [-0.14552138 -0.15909803 -0.15690944 ... -0.38883626  1.78292374
  -0.62750131]
 ...
 [-0.14552138 -0.15909803 -0.15690944 ... -0.38883626 -0.56087649
   0.69067666]
 [-0.14552138 -0.15909803 -0.15690944 ... -0.38883626 -0.56087649
  -1.68204368]
 [-0.14552138 -0.15909803 -0.15690944 ... -0.38883626 -0.56087649
  -0.10023012]]


In [7]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score,confusion_matrix
rg=RandomForestRegressor(n_estimators=1000,random_state=42)
rg.fit(Xtrain,Ytrain)
ypred=rg.predict(Xtest)
print(r2_score(Ytest,ypred))

0.4167408692404253


In [8]:
from xgboost import XGBRegressor
xgbr=XGBRegressor()
xgbr.fit(Xtrain,Ytrain)
ypred=xgbr.predict(Xtest)
print(r2_score(Ytest,ypred))


0.5904710325720552
